name: Build and Release

on:
  workflow_dispatch: 
    inputs:
      tag:
        description: 'Tag name'     
        required: true
      note:
        description: 'Release note'
        
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup_node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm i -g @vercel/ncc
          npm i @actions/github
          npm run build
      - name: Commit
        run: |
          git config --global user.name 'howtt8998'
          git config --global user.email 'ht.howardtan@gmail.com'
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -am "dist build"
            git push || echo "No changes to push."
          else
            echo "No changes to commit."
          fi

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Test index.js
        env:
          INPUT_GITHUB_USERNAME: 'howtt8998'
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Fixed the token issue
          INPUT_TARGET_REPOS: '[howtt8998/activity-log]'
          INPUT_OUTPUT_STYLE: MARKDOWN
          INPUT_IGNORE_EVENTS: '[]'
          INPUT_README_PATH: README.md
          INPUT_COMMIT_MESSAGE: Update README.md
          INPUT_EVENT_LIMIT: '100'
        run: node ./dist/index.js

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Pull latest
        run: |
          git config --global user.name 'howtt8998'
          git config --global user.email 'ht.howardtan@gmail.com'
          git pull
      - name: Tag it
        run: |
          git tag -a ${{ inputs.tag }} -m "更新標籤" master # Use the input tag value
          git push --tags -f
      - name: Release
        uses: actions/create-release@v1.0.0 # Updated action version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: Release ${{ inputs.tag }}
          body: ${{ inputs.note }}
          draft: false
          prerelease: false
